version: '3.7'

services:
  minecraft:
    build: .
    hostname: minecraft-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
    - JAVA_XMS=${JAVA_XMS}
    - JAVA_XMX=${JAVA_XMX}
    - MINECRAFT_VERSION=${MINECRAFT_VERSION}
    ports:
      - "25565:25565"
    volumes:
      - minecraft:/root/minecraft

volumes:
  minecraft: