version: '3.7'

services:
  minecraft:
    build: .
    hostname: minecraft-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
    - JAVA_XMS=2048M
    - JAVA_XMX=2048M
    - MINECRAFT_VERSION=1.19.4
    ports:
      - "25565:25565"
    volumes:
      - minecraft:/root/minecraft

volumes:
  minecraft: